# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='authy_status',
        ),
    ]
